server:
    port: 9000

jwt:
    secret: secretkey123

spring:
    application:
        name: SUBSCRIPTION_API_GATEWAY_JWT

    cloud:
        gateway:
            discovery:
              locator:
                enabled: true
            routes:
            - id: SUBSCRIBER-SERVICE
              uri: 
                lb://SUBSCRIBER-SERVICE
              predicates: 
              - Path=/subscriber/**
              
            - id: PLAN-SERVICE
              uri: 
                lb://PLAN-SERVICE
              predicates: 
              - Path=/plans/**

    main: 
      web-application-type: 
                      reactive