server:
    port: 9000

jwt:
    secret: secretkey123

spring:
    application:
        name: SUBSCRIPTION_API_GATEWAY_JWT

    cloud:
        gateway:
            discovery:
              locator:
                enabled: true
            routes:
            - id: SUBSCRIBER-SERVICE
              uri: 
                lb://SUBSCRIBER-SERVICE
              predicates: 
              - Path=/subscriber/**
              
            - id: PLAN-SERVICE
              uri: 
                lb://PLAN-SERVICE
              predicates: 
              - Path=/plans/**

    main: 
      web-application-type: 
                      reactive
      allow-bean-definition-overriding: true
    datasource:
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/plan_model
      username: root
      password: nabeel
    jpa:
        hibernate.ddl-auto: update
        generate-ddl: true
        show-sql: true
    
    #eureka.client.service-url.default-zone
eureka:
      client:
        service-url:
          default-zone: http://localhost:8761/eureka
      instance:
        instance-id: ${spring.application.name}:${random.value}

csrf:
  protection:
    enabled: false